var etiquetas = {
  "carrera": {
    "1": "Agronomía e Ingeniería Forestal",
    "2": "Bioingeniería",
    "3": "Geología",
    "4": "Ingeniería Aeronáutica",
    "5": "Ingeniería Agrícola",
    "6": "Ingeniería Agrícola M/ Ganadería",
    "7": "Ingeniería Agroindustrial",
    "8": "Ingeniería Agronómica",
    "9": "Ingeniería Ambiental",
    "10": "Ingeniería Bioinformática",
    "11": "Ingeniería Civil",
    "12": "Ingeniería Civil Acústica",
    "13": "Ingeniería Civil Aereoespacial",
    "14": "Ingeniería Civil Agrícola",
    "15": "Ingeniería Civil Agroindustrias",
    "16": "Ingeniería Civil Ambiental",
    "17": "Ingeniería Civil Biomédica",
    "18": "Ingeniería Civil Bioquímica",
    "19": "Ingeniería Civil Biotecnología",
    "20": "Ingeniería Civil Biotecnología Acuícola",
    "21": "Ingeniería Civil Eléctrica",
    "22": "Ingeniería Civil Electrónica",
    "23": "Ingeniería Civil en Automatización",
    "24": "Ingeniería Civil en Computación",
    "25": "Ingeniería Civil en Computación e Informática",
    "26": "Ingeniería Civil en Construcción",
    "27": "Ingeniería Civil en Geografía",
    "28": "Ingeniería Civil en Matemáticas",
    "29": "Ingeniería Civil en Materiales",
    "30": "Ingeniería Civil en Metalurgia",
    "31": "Ingenieria Civil en Metalurgia Extractiva",
    "32": "Ingeniería Civil en Minas",
    "33": "Ingeniería Civil en Obras Civiles ",
    "34": "Ingeniería Civil en Procesos Minerales",
    "35": "Ingeniería Civil en Sonido y Acústica",
    "36": "Ingeniería Civil en Telecomunicaciones",
    "37": "Ingeniería Civil Estructural",
    "38": "Ingeniería Civil Geológica",
    "39": "Ingeniería Civil Geomática",
    "40": "Ingeniería Civil Hidráulica",
    "41": "Ingeniería Civil Industrial",
    "42": "Ingeniería Civil Industrial - Agroindustrias",
    "43": "Ingeniería Civil Industrial - Bioprocesos",
    "44": "Ingeniería Civil Industrial - Electricidad",
    "45": "Ingeniería Civil Industrial - Electrónica",
    "46": "Ingeniería Civil Industrial - Informática",
    "47": "Ingeniería Civil Industrial - Mecánica",
    "48": "Ingeniería Civil Industrial - Minas",
    "49": "Ingeniería Civil Industrial - Sistemas de Gestión",
    "50": "Ingeniería Civil Industrias de la Madera",
    "51": "Ingeniería Civil Informática",
    "52": "Ingeniería Civil Informática y Telecomunicaciones",
    "53": "Ingeniería Civil Logística",
    "54": "Ingeniería Civil Mecánica",
    "55": "Ingeniería Civil Oceánica",
    "56": "Ingeniería Civil Química",
    "57": "Ingeniería Civil Telemática",
    "58": "Ingeniería Comercial",
    "59": "Ingeniería de Transporte",
    "60": "Ingeniería Ejecución - Administración",
    "61": "Ingeniería Ejecución - Administración de Empresas",
    "62": "Ingeniería Ejecución - Administración de Empresas M/ Finanzas",
    "63": "Ingeniería Ejecución - Administración de Empresas M/ Marketing",
    "64": "Ingeniería Ejecución - Administración de Empresas M/ Recursos Humanos",
    "65": "Ingeniería Ejecución - Administración de Negocios ",
    "66": "Ingeniería Ejecución - Administración de Redes",
    "67": "Ingeniería Ejecución - Administración Pública",
    "68": "Ingeniería Ejecución - Agropecuaria",
    "69": "Ingeniería Ejecución - Bioprocesos",
    "70": "Ingeniería Ejecución - Biotecnología",
    "71": "Ingeniería Ejecución - Climatización",
    "72": "Ingeniería Ejecución - Comercio Internacional",
    "73": "Ingeniería Ejecución - Computación",
    "74": "Ingeniería Ejecución - Computación e Informática",
    "75": "Ingeniería Ejecución - Electricidad",
    "76": "Ingeniería Ejecución - Electrónica",
    "77": "Ingeniería Ejecución - Geomensura",
    "78": "Ingeniería Ejecución - Gestión Deportiva",
    "79": "Ingeniería Ejecución - Industrial",
    "80": "Ingeniería Ejecución - Informática",
    "81": "Ingeniería Ejecución - Informática M/ Base de Datos",
    "82": "Ingeniería Ejecución - Informática M/ Desarrollo de Sistemas",
    "83": "Ingeniería Ejecución - Informática M/ Seguridad",
    "84": "Ingeniería Ejecución - Mecánica",
    "85": "Ingeniería Ejecución - Mecánica de Procesos y Mant. Industrial",
    "86": "Ingeniería Ejecución - Metalurgia",
    "87": "Ingeniería Ejecución - Minas",
    "88": "Ingeniería Ejecución - Prevención de Riesgos y Medio Ambiente",
    "89": "Ingeniería Ejecución - Química",
    "90": "Ingeniería Ejecución - Redes M/ Telecomunicaciones",
    "91": "Ingeniería Ejecución - Sonido",
    "92": "Ingeniería Ejecución - Web Manager ",
    "93": "Ingeniería Eléctrica",
    "94": "Ingeniería Electrónica",
    "95": "Ingeniería en  Redes y Telecomunicaciones",
    "96": "Ingeniería en Acuicultura",
    "97": "Ingeniería en Administración ",
    "98": "Ingeniería en Administración Agroindustrial",
    "99": "Ingeniería en Administración de Empresas",
    "100": "Ingeniería en Administración de Empresas Financieras",
    "101": "Ingeniería en Administración de Empresas M/ Finanzas",
    "102": "Ingeniería en Administración de Empresas M/ Gestión de Personas",
    "103": "Ingeniería en Administración de Empresas M/ Logística",
    "104": "Ingeniería en Administración de Empresas M/ Marketing",
    "105": "Ingeniería en Administración de Empresas M/ Recursos Humanos",
    "106": "Ingeniería en Administración de Negocios y Gestión Comercial",
    "107": "Ingeniería en Administración de Recursos Humanos",
    "108": "Ingeniería en Administración Hotelera Internacional",
    "109": "Ingeniería en Administración Industrial M/ Procesos Productivos",
    "110": "Ingeniería en Administración M/ Finanzas",
    "111": "Ingeniería en Administración M/ Marketing",
    "112": "Ingeniería en Administración Pública y Municipal",
    "114": "Ingeniería en Agronegocios",
    "115": "Ingeniería en Alimentos",
    "116": "Ingeniería en Automatización y Control Industrial",
    "117": "Ingeniería en Automatización y Robótica ",
    "118": "Ingeniería en Aviación Comercial",
    "119": "Ingeniería en Biotecnología",
    "120": "Ingeniería en Biotecnología Marina y Acuicultura",
    "121": "Ingeniería en Biotecnología Molecular",
    "122": "Ingeniería en Biotecnología Vegetal",
    "123": "Ingeniería en Climatización",
    "124": "Ingeniería en Comercio Exterior",
    "125": "Ingeniería en Comercio Internacional",
    "126": "Ingeniería en Computación",
    "127": "Ingeniería en Computación e Informática",
    "128": "Ingeniería en Conectividad y Redes",
    "129": "Ingeniería en Conservación de Recursos Naturales",
    "130": "Ingeniería en Construcción",
    "131": "Ingeniería en Construcción Civil",
    "132": "Ingeniería en Control de Gestión",
    "133": "Ingeniería en Diseño de Productos",
    "134": "Ingeniería en Eco Energías",
    "135": "Ingeniería en Electricidad M/ Potencia",
    "136": "Ingeniería en Electricidad M/ Proyectos de Instalaciones Eléctricas",
    "137": "Ingeniería en Electricidad y Automatización Industrial",
    "138": "Ingeniería en Electricidad y Electrónica",
    "139": "Ingeniería en Electricidad y Electrónica Industrial",
    "140": "Ingeniería en Electrónica y Telecomunicaciones",
    "141": "Ingeniería en Estadística",
    "142": "Ingeniería en Expediciones y Ecoturismo",
    "143": "Ingeniería en Fabricación y Diseño Industrial",
    "144": "Ingeniería en Finanzas",
    "145": "Ingeniería en Geomensura",
    "146": "Ingeniería en Geomensura y Cartografía",
    "147": "Ingeniería en Gestión Comercial",
    "148": "Ingeniería en Gestión de Empresas",
    "149": "Ingeniería en Gestión de Marketing",
    "150": "Ingeniería en Gestión de Negocios",
    "151": "Ingeniería en Gestión de Recursos Humanos",
    "152": "Ingeniería en Gestión de Tecnologías de la Información",
    "153": "Ingeniería en Gestión Financiera",
    "154": "Ingeniería en Gestión Informática ",
    "155": "Ingeniería en Gestión Logística",
    "156": "Ingeniería en Gestión Turística",
    "157": "Ingeniería en Hotelería y Turismo",
    "158": "Ingeniería en Industria Alimentaria",
    "159": "Ingeniería en Industria de la Madera",
    "160": "Ingeniería en Información y Control de Gestión",
    "161": "Ingeniería en Información y Control de Gestión y/o Auditoría",
    "162": "Ingeniería en Informática",
    "163": "Ingeniería en Informática Empresarial",
    "164": "Ingeniería en Infraestructura y Plataformas Tecnológicas",
    "165": "Ingeniería en Investigación Criminal",
    "166": "Ingeniería en Investigación Policial",
    "167": "Ingeniería en Logística y Transporte",
    "168": "Ingeniería en Mantenimiento Industrial",
    "169": "Ingeniería en Maquinaria Pesada y Vehículos Automotrices",
    "170": "Ingeniería en Maquinaria y Vehículos Pesados",
    "171": "Ingeniería en Maquinaria, Vehículos Automotrices y Sistemas Electrónicos",
    "172": "Ingeniería en Marina Mercante",
    "173": "Ingeniería en Marketing",
    "174": "Ingeniería en Mecánica",
    "175": "Ingeniería en Mecánica Automotriz y Autotrónica",
    "176": "Ingeniería en Mecatrónica",
    "177": "Ingeniería en Medio Ambiente",
    "178": "Ingeniería en Medio Ambiente y Recursos naturales",
    "179": "Ingeniería en Metalurgia",
    "180": "Ingeniería en Minas",
    "181": "Ingeniería en Negocios Internacionales",
    "182": "Ingeniería en Prevención de Riesgos",
    "183": "Ingeniería en Prevención de Riesgos Laborales y Ambientales",
    "184": "Ingeniería en Prevención de Riesgos y Med.Ambiente",
    "185": "Ingeniería en Prevención de Riesgos, Calidad y Ambiente",
    "186": "Ingeniería en Química",
    "187": "Ingeniería en Química Industrial",
    "188": "Ingeniería en Química y Medio Ambiente",
    "189": "Ingeniería en Recursos Humanos",
    "190": "Ingeniería en Recursos Naturales",
    "191": "Ingeniería en Recursos Naturales Renovables",
    "192": "Ingeniería en Redes y Comunicaciones",
    "193": "Ingeniería en Refrigeración",
    "194": "Ingeniería en Seguridad y Prev. de Riesgos",
    "195": "Ingeniería en Sistemas de Información y Control de Gestión",
    "196": "Ingeniería en Sonido",
    "197": "Ingeniería en Sonido y Acústica",
    "198": "Ingeniería en Telecomunicaciones",
    "199": "Ingeniería en Telecomunicaciones, Conectividad y Redes",
    "200": "Ingeniería en Transporte Marítimo",
    "201": "Ingeniería en Transporte Marítimo y Puertos",
    "202": "Ingeniería en Transporte y Tránsito",
    "203": "Ingeniería en Turismo",
    "204": "Ingeniería en Turismo y Hotelería",
    "205": "Ingeniería Estadística",
    "206": "Ingeniería Financiera",
    "207": "Ingeniería Física",
    "208": "Ingeniería Forestal",
    "209": "Ingeniería Geológica",
    "210": "Ingeniería Geomática",
    "211": "Ingeniería Industrial",
    "212": "Ingeniería Matemática",
    "213": "Ingeniería Mecánica",
    "214": "Ingeniería Mecánica Automotriz y Autotrónica",
    "215": "Ingeniería Mecánica en Mantenimiento Industrial",
    "216": "Ingeniería Mecánica en Producción Industrial",
    "217": "Ingeniería Mecánica Industrial",
    "218": "Ingeniería Mecánica y Mecatrónica",
    "219": "Ingeniería Naval (y sus menciones)",
    "220": "Ingeniería Pesquera",
    "221": "Ingeniería Politécnica Militar (y sus menciones)",
    "222": "Ingeniería Química Ambiental",
    "223": "Ingeniería en Informática y Multimedia"
  },
  "industria": {
    "1": "Academia",
    "2": "Acuícola",
    "3": "Administración",
    "4": "Administración Pública",
    "5": "Agrícola",
    "6": "Alimentos",
    "7": "Arte/Diseño",
    "8": "Auditoría",
    "9": "Automotriz",
    "10": "Bancaria / Financiera",
    "11": "Combustible",
    "12": "Comunicación",
    "13": "Construcción - Industrial",
    "14": "Construcción - Inmobiliaria",
    "15": "Construcción - Vial",
    "16": "Defensa",
    "17": "Educación / Capacitación",
    "18": "Energía",
    "19": "Entretención",
    "20": "Farmacéutica",
    "21": "Forestal",
    "22": "Ganadera",
    "23": "Industrial / Productiva",
    "24": "Informática / TI",
    "25": "Ingeniería",
    "26": "Inteligencia de Negocios",
    "27": "Legal",
    "28": "Logística / Distribución",
    "29": "Mantención",
    "30": "Manufactura",
    "31": "Maquinaria",
    "32": "Marítima",
    "33": "Marketing",
    "34": "Medicina / Salud",
    "35": "Medio Ambiente",
    "36": "Minería",
    "37": "Montaje Industrial",
    "38": "Pesca",
    "39": "Portuaria",
    "40": "Química",
    "41": "Recursos Humanos",
    "42": "Retail",
    "43": "Sanitarias",
    "44": "Seguridad",
    "45": "Servicios a clientes",
    "46": "Telecomunicaciones",
    "47": "Transporte",
    "48": "Turismo",
    "49": "Ventas",
    "50": "Videojuegos",
    "51": "Abastecimiento",
    "52": "I+D"
  },
  "institucion": {
    "1": "Pontificia Universidad Católica de Chile",
    "2": "Pontificia Universidad Católica de Valparaíso",
    "3": "U. Católica Cardenal Raúl Silva Henriquez ",
    "4": "Universidad Academia de Humanismo Cristiano",
    "5": "Universidad Adolfo Ibañez",
    "6": "Universidad Adventista de Chile",
    "7": "Universidad Alberto Hurtado ",
    "8": "Universidad Andrés Bello",
    "9": "Universidad Arturo Prat",
    "10": "Universidad Austral de Chile",
    "11": "Universidad Autónoma de Chile",
    "12": "Universidad Bernardo O´Higgins",
    "13": "Universidad Bolivariana",
    "14": "Universidad Católica de la Santísima Concepción",
    "15": "Universidad Católica de Temuco",
    "16": "Universidad Católica del Maule",
    "17": "Universidad Católica del Norte",
    "18": "Universidad Central",
    "19": "Universidad de Aconcagua",
    "20": "Universidad de Antofagasta",
    "21": "Universidad de Atacama",
    "22": "Universidad de Chile",
    "23": "Universidad de Concepción",
    "24": "Universidad de la Frontera",
    "25": "Universidad de la Serena",
    "26": "Universidad de Las Américas",
    "27": "Universidad de los Andes",
    "28": "Universidad de Los Lagos",
    "29": "Universidad de Magallanes",
    "30": "Universidad de Playa Ancha",
    "31": "Universidad de Santiago",
    "32": "Universidad de Talca",
    "33": "Universidad de Tarapacá",
    "34": "Universidad de Valparaíso",
    "35": "Universidad de Viña del Mar",
    "36": "Universidad del Bío-Bío",
    "37": "Universidad del Desarrollo",
    "38": "Universidad del Mar",
    "39": "Universidad del Mar - Sede Iquique",
    "40": "Universidad del Pacífico",
    "41": "Universidad Diego Portales",
    "42": "Universidad Finis Terrae",
    "43": "Universidad Gabriela Mistral",
    "44": "Universidad Iberoamericana",
    "45": "Universidad Internacional SEK",
    "46": "Universidad Los Leones",
    "47": "Universidad Mayor",
    "48": "Universidad Miguel de Cervantes",
    "49": "Universidad Pedro de Valdivia",
    "50": "Universidad San Sebastián",
    "51": "Universidad Santo Tomás",
    "52": "Universidad Téc. Federico Sta. María",
    "53": "Universidad Tecnológica Metropolitana",
    "54": "Universidad UCINF",
    "55": "INACAP",
    "56": "Instituto de Estudios Bancarios Guillermo Subercaseaux",
    "57": "Instituto Profesional AIEP",
    "58": "Instituto Profesional ARCOS",
    "59": "Instituto Profesional Carlos Casanueva",
    "60": "Instituto Profesional Diego Portales",
    "61": "Instituto Profesional Virginio Gomez",
    "62": "Instituto Profesional CIISA",
    "63": "Instituto Profesional de Chile",
    "64": "Instituto Profesional del Valle Central",
    "65": "Instituto Profesional DUOC UC",
    "66": "Instituto Profesional ESUCOMEX",
    "67": "Instituto Profesional IPG",
    "68": "Instituto Profesional IPLACEX",
    "69": "Instituto Profesional La Araucana",
    "70": "Instituto Profesional Los Leones",
    "71": "Instituto Profesional Providencia",
    "72": "Academia Politécnica Aeronáutica",
    "73": "Academia Politécnica de Ciencias Policiales de Carabineros de Chile",
    "74": "Academia Politécnica Militar",
    "75": "Academia Politécnica Naval",
    "76": "Otra Casa de Estudio",
    "77": "UNIACC"
  },
  "cargo": {
    "1": "Analista / Ingeniero Junior",
    "2": "Ingeniero Senior",
    "3": "Jefe",
    "4": "Consultor Junior",
    "5": "Consultor Senior",
    "6": "Subgerente",
    "7": "Gerente",
    "8": "Gerente General",
    "9": "Independiente"
  },
  "genero": {
    "1": "M",
    "2": "F"
  }
};

module.exports.etiquetas = etiquetas;